# Generated by Django 3.2.16 on 2023-01-02 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入职时间'),
        ),
    ]
