# Generated by Django 3.2.16 on 2023-01-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='author',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
